// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDll6nAjuw-wiTgt9Bw5n6JayqnBXQlKho',
    appId: '1:527891949299:web:8358bcb6beb1453c0d3986',
    messagingSenderId: '527891949299',
    projectId: 'perfum-5b31c',
    authDomain: 'perfum-5b31c.firebaseapp.com',
    storageBucket: 'perfum-5b31c.firebasestorage.app',
    measurementId: 'G-KWWJPC908T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Bm7ktcwC6FyRB-D_2xdpm-VfmhlLpsE',
    appId: '1:527891949299:android:d2c7a3a9764626380d3986',
    messagingSenderId: '527891949299',
    projectId: 'perfum-5b31c',
    storageBucket: 'perfum-5b31c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3JL9oGc7y6V2TOjWDo0BXBjjE44x91A',
    appId: '1:527891949299:ios:41c4418e43d5edfa0d3986',
    messagingSenderId: '527891949299',
    projectId: 'perfum-5b31c',
    storageBucket: 'perfum-5b31c.firebasestorage.app',
    iosBundleId: 'com.example.perfume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX3JL9oGc7y6V2TOjWDo0BXBjjE44x91A',
    appId: '1:527891949299:ios:41c4418e43d5edfa0d3986',
    messagingSenderId: '527891949299',
    projectId: 'perfum-5b31c',
    storageBucket: 'perfum-5b31c.firebasestorage.app',
    iosBundleId: 'com.example.perfume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDll6nAjuw-wiTgt9Bw5n6JayqnBXQlKho',
    appId: '1:527891949299:web:9ce75c0cecf3dc920d3986',
    messagingSenderId: '527891949299',
    projectId: 'perfum-5b31c',
    authDomain: 'perfum-5b31c.firebaseapp.com',
    storageBucket: 'perfum-5b31c.firebasestorage.app',
    measurementId: 'G-DJ3N15VDRR',
  );
}
