class AppConstants {
  // App info
  static const String appName = 'أثير';
  static const String appVersion = '1.0.0';
  static const int updateCheckIntervalHours = 24;

  // OTA/Firebase remote update
  static const String firebaseConfigCollection = 'app_config';
  static const String firebaseConfigDocument = 'android';
  static const String apkFileName = 'atheer-release.apk';
  static const int connectionTimeoutSeconds = 30;
  static const int receiveTimeoutSeconds = 120;
  static const int maxUpdateRetries = 3;
  static const int retryBaseDelayMs = 1500;

  // Collections
  static const String usersCollection = 'users';
  static const String storesCollection = 'stores';
  static const String perfumesCollection = 'perfumes';
  static const String recommendationsCollection = 'recommendations';
  static const String eegResultsCollection = 'eeg_results';
  static const String eegStatsCollection = 'eeg_stats';
  static const String storeUsersCollection = 'store_users';
  static const String adminUsersCollection = 'admin_users';

  // Shared preferences keys
  static const String userIdKey = 'user_id';
  static const String storeIdKey = 'store_id';
  static const String setupCompleteKey = 'setup_complete';
  static const String lastUpdateCheckKey = 'last_update_check';

  // OTA status messages
  static const String errorFirebaseInit = 'فشل في تهيئة Firebase';
  static const String errorNetwork = 'مشكلة في الاتصال بالشبكة';
  static const String errorDownload = 'فشل في تحميل التحديث';
  static const String errorInstall = 'فشل في تثبيت التحديث';
  static const String errorPermission = 'صلاحيات التثبيت غير متوفرة';
  static const String successUpdate = 'تم التحديث بنجاح';
  static const String successNoUpdate = 'التطبيق محدث';

  // Gender options
  static const String genderMale = 'ذكر';
  static const String genderFemale = 'أنثى';
  static const String genderUnisex = 'للجنسين';
  static const List<String> genderOptions = [
    genderMale,
    genderFemale,
    genderUnisex,
  ];

  // App texts
  static const Map<String, String> arabicTexts = {
    // General
    'welcome': 'مرحباً',
    'continue': 'متابعة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'loading': 'جارٍ التحميل...',
    'error': 'حدث خطأ',
    'success': 'تم بنجاح',
    'confirm': 'تأكيد',
    'try_again': 'حاول مجدداً',
    'close': 'إغلاق',
    'unknown': 'غير معروف',
    'something_went_wrong': 'حدث خطأ ما',
    'no_data_available': 'لا توجد بيانات متاحة',
    'all': 'الكل',
    'language': 'اللغة',
    'change_language': 'تغيير اللغة',
    'arabic': 'العربية',
    'english': 'English',

    // Splash
    'app_title_line_1': 'أثير',
    'app_title_line_2': 'مستشارك العطري',
    'app_tagline': 'اكتشف عطرك المثالي\nبقوة الذكاء الاصطناعي',
    'get_started': 'ابدأ الآن',
    'discover_ideal_perfume': 'اكتشف عطرك المثالي',
    'analyze_brain_waves': 'بتحليل موجاتك الدماغية',
    'start_journey': 'ابدأ الرحلة',
    'copyright_neuroscent':
        'جميع الحقوق محفوظة فكرة و تنفيذ المهندس محمد روحي | © 2025 Neuro-Scent',

    // Auth
    'phone_number': 'رقم الهاتف',
    'enter_phone': 'أدخل رقم هاتفك',
    'name': 'الاسم',
    'enter_name': 'أدخل اسمك',
    'gender': 'الجنس',
    'select_gender': 'اختر الجنس',
    'failed_sign_in': 'فشل تسجيل الدخول',
    'phone_required': 'يرجى إدخال رقم الهاتف',
    'phone_invalid': 'يرجى إدخال رقم هاتف صحيح',
    'verify_phone': 'تأكيد الهاتف',
    'enter_otp': 'أدخل رمز التحقق المكون من 6 أرقام',
    'invalid_code': 'رمز غير صحيح، حاول مرة أخرى',
    'resend_code': 'إعادة إرسال الرمز',
    'code_resent': 'تمت إعادة إرسال الرمز بنجاح',
    'tell_us_about_yourself': 'أخبرنا عنك',
    'your_name': 'اسمك',
    'start_quiz': 'ابدأ الاختبار',
    'additional_info': 'معلومات إضافية',
    'you_can_skip_info': 'يمكنك تخطي هذه المعلومات إذا أردت',
    'optional_name': 'الاسم (اختياري)',
    'country': 'الدولة',
    'qatar': 'قطر',
    'jordan': 'الأردن',
    'saudi_arabia': 'السعودية',
    'uae': 'الإمارات',
    'skip': 'تخطي',
    'skip_info_hint': 'يمكنك تخطي هذه المعلومات والعودة لاحقاً',
    'session_creation_failed': 'فشل إنشاء جلسة المستخدم',
    'please_select': 'الرجاء اختيار',
    'gender_male': 'ذكر',
    'gender_female': 'أنثى',
    'gender_unisex': 'للجنسين',

    // Store
    'store_setup': 'إعداد المتجر',
    'store_code': 'رمز المتجر',
    'enter_store_code': 'أدخل رمز المتجر',
    'invalid_store': 'رمز المتجر غير صحيح',
    'store_not_configured': 'الجهاز غير مهيأ لأي براند',
    'failed_load_store': 'فشل تحميل المتجر',
    'store_name': 'اسم المتجر',
    'address': 'العنوان',
    'logo_url_optional': 'رابط الشعار (اختياري)',
    'create_store': 'إنشاء متجر',
    'add_store': 'إضافة متجر',
    'edit_store': 'تعديل المتجر',
    'failed_create_store': 'فشل إنشاء المتجر',
    'store_name_required': 'الرجاء إدخال اسم المتجر',
    'unique_store_code': 'رمز المتجر الفريد',
    'store_active': 'المتجر نشط',
    'update': 'تحديث',
    'add': 'إضافة',
    'operation_failed': 'فشلت العملية',
    'update_failed': 'فشل التحديث',
    'delete_failed': 'فشل الحذف',
    'confirm_delete_store': 'هل أنت متأكد من حذف هذا المتجر؟',
    'code_copied': 'تم نسخ الرمز: ',
    'code_label': 'الرمز: ',

    // Questionnaire
    'question': 'السؤال',
    'of': 'من',
    'previous': 'السابق',
    'next': 'التالي',
    'analysis_complete': 'اكتمل التحليل!',
    'analyzed_preferences': 'قمنا بتحليل تفضيلاتك',
    'see_recommendation': 'شاهد توصيتك',

    // Recommendation
    'your_perfect_scent': 'عطرك المثالي',
    'you_might_also_like': 'قد يعجبك أيضاً',
    'share': 'مشاركة',
    'finding_scent': 'جارٍ البحث عن عطرك المثالي...',
    'no_recommendation_available': 'لا توجد توصية متاحة',
    'invalid_recommendation_response': 'استجابة توصية غير صالحة',

    // Admin
    'stores': 'المتاجر',
    'users': 'المستخدمين',
    'perfumes': 'العطور',
    'add_perfume': 'إضافة عطر',
    'edit_perfume': 'تعديل العطر',
    'delete_perfume': 'حذف العطر',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'total_perfumes': 'إجمالي العطور',
    'brand_name': 'اسم الماركة',
    'brand_id': 'معرف الماركة',
    'family': 'العائلة',
    'sub_family': 'العائلة الفرعية',
    'intensity': 'القوة',
    'sweetness': 'الحلاوة',
    'freshness': 'الانتعاش',
    'warmth': 'الدفء',
    'notes': 'النوتات',
    'image_url': 'رابط الصورة',
    'description': 'الوصف',
    'save_perfume': 'حفظ العطر',
    'save_changes': 'حفظ التعديلات',
    'select_store_to_manage_perfumes': 'اختر متجراً لإدارة العطور',
    'no_perfumes_yet': 'لا توجد عطور بعد. أضف أول عطر!',
    'notes_comma_separated': 'النوتات (مفصولة بفاصلة)',
    'required_field': 'هذا الحقل مطلوب',
    'failed_update_perfume': 'فشل تحديث العطر',
    'failed_delete_perfume': 'فشل حذف العطر',
    'failed_add_perfume': 'فشل إضافة العطر',
    'search_perfume': 'بحث عن عطر...',
    'filter_by': 'تصفية حسب:',
    'fragrance_family': 'العائلة العطرية',
    'status': 'الحالة',
    'no_perfumes': 'لا توجد عطور',
    'add_first_perfume_now': 'أضف أول عطر الآن',
    'manage_store_perfumes': 'إدارة عطور',
    'eeg_stats': 'إحصائيات EEG',

    // Reports
    'reports': 'التقارير',
    'analytics': 'التحليلات',
    'total_users': 'إجمالي المستخدمين',
    'active_stores': 'المتاجر النشطة',
    'total_recommendations': 'إجمالي التوصيات',
    'new_users_month': 'مستخدمون جدد (الشهر)',
    'perfume_family_distribution': 'توزيع العائلات العطرية',
    'personality_traits': 'السمات الشخصية',
    'sensory_preferences': 'التفضيلات الحسية',
    'recent_recommendations': 'آخر التوصيات',
    'export_csv': 'تصدير CSV',
    'refresh': 'تحديث',
    'export_successful': 'تم التصدير بنجاح',
    'no_rows_to_export': 'لا توجد بيانات للتصدير.',
    'csv_generated': 'تم إنشاء CSV.',
    'minutes_ago': 'دقيقة',
    'hours_ago': 'ساعة',
    'days_ago': 'يوم',

    // Families/traits display
    'family_fresh': 'منعش',
    'family_floral': 'زهري',
    'family_oriental': 'شرقي',
    'family_woody': 'خشبي',
    'family_fern': 'سرخسي',
    'trait_openness': 'الانفتاح',
    'trait_extraversion': 'الانبساط',
    'trait_neuroticism': 'الحساسية',
    'admin_dashboard': 'لوحة تحكم المدير',
    'advanced_reports': 'تقارير متقدمة',
    'manage_users': 'إدارة المستخدمين',
    'system_update': 'تحديث النظام',
    'app_update_available': 'تحديث التطبيق • إصدار جديد متاح',
    'no_stores_yet': 'لا توجد متاجر بعد',
    'click_plus_add_store': 'انقر على + لإضافة متجر جديد',
    'choose_store': 'اختر متجراً',
    'choose_store_manage_perfumes':
        'اختر متجراً من القائمة الجانبية لإدارة العطور',
    'settings': 'الإعدادات',

    // EEG visualization
    'eeg_ready_to_start': 'جاهز للبدء',
    'eeg_connecting': 'جاري الاتصال',
    'eeg_reading_waves': 'قراءة الموجات',
    'eeg_processing_data': 'تحليل البيانات',
    'eeg_analysis_complete': 'اكتمل التحليل',
    'eeg_click_start': 'انقر على زر البدء',
    'eeg_connect_sensor': 'تأكد من توصيل جهاز المستشعر',
    'eeg_relax_focus_perfume': 'استرخِ وركز على العطر',
    'eeg_processing_signals': 'جاري معالجة الإشارات العصبية',
    'eeg_response_analyzed': 'تم تحليل استجابتك بنجاح',
    'signal_strength': 'قوة الإشارة',
    'wave_coherence': 'تماسك الموجات',
    'auto_analysis_prefix': 'سيتم التحليل تلقائياً خلال ',
    'auto_analysis_suffix': ' ثانية',
    'start_test': 'ابدأ التجربة',

    // Additional localization keys
    'add_new_store_title': 'إضافة متجر جديد',
    'auto_update_system': 'نظام التحديث التلقائي',
    'average_recommendations': 'متوسط التوصيات',
    'avg_interest': 'متوسط الاهتمام',
    'basicInfo': 'المعلومات الأساسية',
    'change_file': 'تغيير الملف',
    'clear_date_filter': 'مسح فلتر التاريخ',
    'countries_distribution': 'توزيع البلدان',
    'countryLabel': 'الدولة',
    'current_version_info': 'معلومات الإصدار الحالي',
    'eeg_results_title': 'نتائج EEG',
    'eeg_results_will_appear_after_tests':
        'ستظهر نتائج EEG هنا بعد إجراء الاختبارات',
    'enter_version_name_and_code': 'يرجى إدخال اسم الإصدار ورقمه',
    'example_version_code': 'مثال: 12',
    'example_version_name': 'مثال: 1.2.0',
    'export_pdf': 'تصدير PDF',
    'failed_upload_update': 'فشل رفع التحديث',
    'favorite_family': 'العائلة المفضلة',
    'filter_results': 'تصفية النتائج',
    'from_date': 'من تاريخ',
    'full_report_file': 'ملف التقرير الكامل',
    'gender_distribution': 'توزيع الجنس',
    'genderLabel': 'الجنس',
    'loading_data': 'جاري تحميل البيانات...',
    'max_size_100mb': 'أقصى حجم: 100 MB',
    'metric_attention': 'التركيز',
    'metric_calmness': 'الهدوء',
    'metric_engagement': 'الانخراط',
    'metric_excitement': 'الإثارة',
    'metric_interest': 'الاهتمام',
    'metric_relaxation': 'الاسترخاء',
    'metric_stress': 'التوتر',
    'metrics_comparison': 'المقارنة بين المقاييس',
    'metrics_details': 'تفاصيل المقاييس',
    'nameLabel': 'الاسم',
    'neural_analysis': 'التحليل العصبي',
    'new_user': 'مستخدم جديد',
    'no_data_to_export': 'لا توجد بيانات للتصدير',
    'no_eeg_results_for_perfume': 'لا توجد نتائج EEG لهذا العطر',
    'outer_values_mean_higher': 'القيم الأقرب للخارج تعني أعلى',
    'pdf_export_error': 'خطأ أثناء تصدير PDF',
    'perfume_singular': 'عطر',
    'perfumes_distribution_by_store': 'توزيع العطور حسب المتجر',
    'personalityAnalysis': 'تحليل الشخصية',
    'phoneLabel': 'رقم الهاتف',
    'profile_complete': 'مكتمل',
    'profile_incomplete': 'غير مكتمل',
    'profile_status': 'حالة الملف الشخصي',
    'recommendations': 'التوصيات',
    'registrationDateLabel': 'تاريخ التسجيل',
    'release_date': 'تاريخ الإصدار',
    'reports_and_analytics': 'التقارير والتحليلات',
    'results_summary': 'ملخص النتائج',
    'search_name_phone': 'ابحث بالاسم أو رقم الهاتف...',
    'select_apk_file': 'اختر ملف APK',
    'select_apk_file_first': 'اختر ملف APK أولاً',
    'sensoryPreferencesTitle': 'التفضيلات الحسية',
    'statsTitle': 'الإحصائيات',
    'this_month': 'هذا الشهر',
    'this_week': 'هذا الأسبوع',
    'this_year': 'هذه السنة',
    'to_date': 'إلى تاريخ',
    'total_tests': 'إجمالي التجارب',
    'traitFreshness': 'الانتعاش',
    'traitIntensity': 'القوة',
    'traitSweetness': 'الحلاوة',
    'traitWarmth': 'الدفء',
    'unknownValue': 'غير معروف',
    'unspecifiedValue': 'غير محدد',
    'upload_new_update': 'رفع تحديث جديد',
    'upload_update': 'رفع التحديث',
    'update_uploaded_successfully': 'تم رفع التحديث بنجاح',
    'uploading_file': 'جاري رفع الملف...',
    'userDetailsFallbackTitle': 'تفاصيل المستخدم',
    'users_activity_by_hour': 'نشاط المستخدمين حسب الساعة',
    'users_distribution': 'توزيع المستخدمين',
    'version_code': 'رقم الإصدار',
    'version_code_must_be_number': 'رقم الإصدار يجب أن يكون رقمًا',
    'version_name': 'اسم الإصدار',
    'store_login_title': 'لوحة تحكم المتجر',
    'store_login_subtitle': 'أدخل بيانات الدخول الخاصة بمتجرك',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'login': 'تسجيل الدخول',
    'please_enter_username': 'الرجاء إدخال اسم المستخدم',
    'please_enter_password': 'الرجاء إدخال كلمة المرور',
    'password_min_6': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'store_dashboard': 'لوحة تحكم',
    'store_singular': 'المتجر',
    'logout': 'تسجيل الخروج',
    'store_not_found': 'لم يتم العثور على المتجر',
    'please_enter_prefix': 'الرجاء إدخال',
    'perfume_name': 'اسم العطر',
    'confirm_delete_perfume_title': 'حذف العطر',
    'confirm_delete_perfume_message': 'هل تريد حذف',
    'upload_perfumes_batch': 'رفع مجموعة عطور',
    'upload_perfumes_batch_hint':
        'حمّل النموذج أولاً لمعرفة الأعمدة المطلوبة، ثم ارفع ملف Excel لإضافة العطور تلقائيًا.',
    'download_template': 'تحميل النموذج',
    'upload_excel': 'رفع Excel',
    'template_downloaded_success': 'تم تنزيل/حفظ نموذج Excel بنجاح.',
    'template_saved_at': 'تم حفظ النموذج في:',
    'template_download_error': 'خطأ في تحميل النموذج',
    'cannot_read_file': 'تعذر قراءة الملف، حاول اختيار ملف آخر.',
    'no_valid_perfumes_in_file': 'لم يتم العثور على عطور صالحة في الملف.',
    'confirm_addition': 'تأكيد الإضافة',
    'found_valid_perfumes': 'تم العثور على عطور صالحة:',
    'invalid_rows': 'صفوف غير صالحة:',
    'add_valid_perfumes_question': 'هل تريد إضافة العطور الصالحة؟',
    'excel_read_error': 'خطأ في قراءة الملف',
    'added_count': 'تمت الإضافة',
    'failed_count': 'فشل',
    'store_login_invalid_username': 'اسم المستخدم غير صحيح',
    'store_login_invalid_password': 'كلمة المرور غير صحيحة',
    'store_login_failed': 'حدث خطأ في تسجيل الدخول',
    'intensity_light': 'خفيف',
    'intensity_medium': 'معتدل',
    'intensity_strong': 'قوي',
    'sweetness_not_sweet': 'غير حلو',
    'sweetness_light_sweet': 'حلو خفيف',
    'sweetness_sweet': 'حلو',
    'sweetness_very_sweet': 'حلو جداً',
    'warmth_cool': 'بارد',
    'warmth_neutral': 'محايد',
    'warmth_warm': 'دافئ',
    'subfamily_floral_soft': 'زهري ناعم',
    'subfamily_floral_oriental': 'زهري شرقي',
    'subfamily_oriental_soft': 'شرقي ناعم',
    'subfamily_oriental_woody': 'شرقي خشبي',
    'subfamily_woods': 'أخشاب',
    'subfamily_mossy_woody': 'طحلبي خشبي',
    'subfamily_dry_woody': 'خشبي جاف',
    'subfamily_citrus': 'حمضيات',
    'subfamily_fruity': 'فواكه',
    'subfamily_green': 'أخضر',
    'subfamily_aquatic': 'مائي',
    'subfamily_fern': 'سرخسي',
  };

  static const Map<String, String> englishTexts = {
    // General
    'welcome': 'Welcome',
    'continue': 'Continue',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'confirm': 'Confirm',
    'try_again': 'Try again',
    'close': 'Close',
    'unknown': 'Unknown',
    'something_went_wrong': 'Something went wrong',
    'no_data_available': 'No data available',
    'all': 'All',
    'language': 'Language',
    'change_language': 'Change Language',
    'arabic': 'Arabic',
    'english': 'English',

    // Splash
    'app_title_line_1': 'Atheer',
    'app_title_line_2': 'Your Perfume Advisor',
    'app_tagline': 'Discover your ideal scent\nwith AI power',
    'get_started': 'Get Started',
    'discover_ideal_perfume': 'Discover your ideal perfume',
    'analyze_brain_waves': 'By analyzing your brain waves',
    'start_journey': 'Start Journey',
    'copyright_neuroscent':
        'All rights reserved. Concept and implementation by Eng. Mohammad Rouhi | © 2025 Neuro-Scent',

    // Auth
    'phone_number': 'Phone Number',
    'enter_phone': 'Enter your phone number',
    'name': 'Name',
    'enter_name': 'Enter your name',
    'gender': 'Gender',
    'select_gender': 'Select gender',
    'failed_sign_in': 'Failed to sign in',
    'phone_required': 'Please enter phone number',
    'phone_invalid': 'Please enter a valid phone number',
    'verify_phone': 'Verify Phone',
    'enter_otp': 'Enter the 6-digit verification code',
    'invalid_code': 'Invalid code, try again',
    'resend_code': 'Resend code',
    'code_resent': 'Code sent again successfully',
    'tell_us_about_yourself': 'Tell us about yourself',
    'your_name': 'Your name',
    'start_quiz': 'Start Quiz',
    'additional_info': 'Additional Information',
    'you_can_skip_info': 'You can skip this information if you want',
    'optional_name': 'Name (optional)',
    'country': 'Country',
    'jordan': 'Jordan',
    'saudi_arabia': 'Saudi Arabia',
    'uae': 'United Arab Emirates',
    'qatar': 'Qatar',
    'skip': 'Skip',
    'skip_info_hint': 'You can skip this information and return later',
    'session_creation_failed': 'Failed to create user session',
    'please_select': 'Please select',
    'gender_male': 'Male',
    'gender_female': 'Female',
    'gender_unisex': 'Unisex',

    // Store
    'store_setup': 'Store Setup',
    'store_code': 'Store Code',
    'enter_store_code': 'Enter store code',
    'invalid_store': 'Invalid store code',
    'store_not_configured': 'Device is not configured for any brand',
    'failed_load_store': 'Failed to load store',
    'store_name': 'Store Name',
    'address': 'Address',
    'logo_url_optional': 'Logo URL (optional)',
    'create_store': 'Create Store',
    'add_store': 'Add Store',
    'edit_store': 'Edit Store',
    'failed_create_store': 'Failed to create store',
    'store_name_required': 'Please enter store name',
    'unique_store_code': 'Unique store code',
    'store_active': 'Store active',
    'update': 'Update',
    'add': 'Add',
    'operation_failed': 'Operation failed',
    'update_failed': 'Update failed',
    'delete_failed': 'Delete failed',
    'confirm_delete_store': 'Are you sure you want to delete this store?',
    'code_copied': 'Code copied: ',
    'code_label': 'Code: ',

    // Questionnaire
    'question': 'Question',
    'of': 'of',
    'previous': 'Previous',
    'next': 'Next',
    'analysis_complete': 'Analysis Complete!',
    'analyzed_preferences': 'We analyzed your preferences',
    'see_recommendation': 'See your recommendation',

    // Recommendation
    'your_perfect_scent': 'Your ideal perfume',
    'you_might_also_like': 'You might also like',
    'share': 'Share',
    'finding_scent': 'Finding your ideal perfume...',
    'no_recommendation_available': 'No recommendation available',
    'invalid_recommendation_response': 'Invalid recommendation response',

    // Admin
    'stores': 'Stores',
    'users': 'Users',
    'perfumes': 'Perfumes',
    'add_perfume': 'Add Perfume',
    'edit_perfume': 'Edit Perfume',
    'delete_perfume': 'Delete Perfume',
    'active': 'Active',
    'inactive': 'Inactive',
    'total_perfumes': 'Total Perfumes',
    'brand_name': 'Brand Name',
    'brand_id': 'Brand ID',
    'family': 'Family',
    'sub_family': 'Sub-family',
    'intensity': 'Intensity',
    'sweetness': 'Sweetness',
    'freshness': 'Freshness',
    'warmth': 'Warmth',
    'notes': 'Notes',
    'image_url': 'Image URL',
    'description': 'Description',
    'save_perfume': 'Save Perfume',
    'save_changes': 'Save Changes',
    'select_store_to_manage_perfumes': 'Select a store to manage perfumes',
    'no_perfumes_yet': 'No perfumes yet. Add the first one!',
    'notes_comma_separated': 'Notes (comma separated)',
    'required_field': 'This field is required',
    'failed_update_perfume': 'Failed to update perfume',
    'failed_delete_perfume': 'Failed to delete perfume',
    'failed_add_perfume': 'Failed to add perfume',
    'search_perfume': 'Search perfume...',
    'filter_by': 'Filter by:',
    'fragrance_family': 'Fragrance family',
    'status': 'Status',
    'no_perfumes': 'No perfumes found',
    'add_first_perfume_now': 'Add your first perfume now',
    'manage_store_perfumes': 'Manage Perfumes',
    'eeg_stats': 'EEG Stats',

    // Reports
    'reports': 'Reports',
    'analytics': 'Analytics',
    'total_users': 'Total Users',
    'active_stores': 'Active Stores',
    'total_recommendations': 'Total Recommendations',
    'new_users_month': 'New Users (Month)',
    'perfume_family_distribution': 'Perfume Family Distribution',
    'personality_traits': 'Personality Traits',
    'sensory_preferences': 'Sensory Preferences',
    'recent_recommendations': 'Recent Recommendations',
    'export_csv': 'Export CSV',
    'refresh': 'Refresh',
    'export_successful': 'Export successful',
    'no_rows_to_export': 'No data to export.',
    'csv_generated': 'CSV generated.',
    'minutes_ago': 'minute',
    'hours_ago': 'hour',
    'days_ago': 'day',

    // Families/traits display
    'family_fresh': 'Fresh',
    'family_floral': 'Floral',
    'family_oriental': 'Oriental',
    'family_woody': 'Woody',
    'family_fern': 'Fern',
    'trait_openness': 'Openness',
    'trait_extraversion': 'Extraversion',
    'trait_neuroticism': 'Neuroticism',
    'admin_dashboard': 'Admin Dashboard',
    'advanced_reports': 'Advanced Reports',
    'manage_users': 'Manage Users',
    'system_update': 'System Update',
    'app_update_available': 'App update • New version available',
    'no_stores_yet': 'No stores yet',
    'click_plus_add_store': 'Tap + to add a new store',
    'choose_store': 'Choose a store',
    'choose_store_manage_perfumes':
        'Choose a store from the sidebar to manage perfumes',
    'settings': 'Settings',

    // EEG visualization
    'eeg_ready_to_start': 'Ready to start',
    'eeg_connecting': 'Connecting',
    'eeg_reading_waves': 'Reading waves',
    'eeg_processing_data': 'Processing data',
    'eeg_analysis_complete': 'Analysis complete',
    'eeg_click_start': 'Tap the start button',
    'eeg_connect_sensor': 'Ensure the sensor is connected',
    'eeg_relax_focus_perfume': 'Relax and focus on the perfume',
    'eeg_processing_signals': 'Processing neural signals',
    'eeg_response_analyzed': 'Your response has been analyzed successfully',
    'signal_strength': 'Signal strength',
    'wave_coherence': 'Wave coherence',
    'auto_analysis_prefix': 'Auto analysis in ',
    'auto_analysis_suffix': ' seconds',
    'start_test': 'Start Test',

    // Additional localization keys
    'add_new_store_title': 'Add New Store',
    'auto_update_system': 'Auto Update System',
    'average_recommendations': 'Average Recommendations',
    'avg_interest': 'Average Interest',
    'basicInfo': 'Basic Information',
    'change_file': 'Change File',
    'clear_date_filter': 'Clear Date Filter',
    'countries_distribution': 'Countries Distribution',
    'countryLabel': 'Country',
    'current_version_info': 'Current Version Information',
    'eeg_results_title': 'EEG Results',
    'eeg_results_will_appear_after_tests':
        'EEG results will appear here after tests',
    'enter_version_name_and_code': 'Please enter version name and code',
    'example_version_code': 'Example: 12',
    'example_version_name': 'Example: 1.2.0',
    'export_pdf': 'Export PDF',
    'failed_upload_update': 'Failed to upload update',
    'favorite_family': 'Favorite Family',
    'filter_results': 'Filter Results',
    'from_date': 'From Date',
    'full_report_file': 'Full Report File',
    'gender_distribution': 'Gender Distribution',
    'genderLabel': 'Gender',
    'loading_data': 'Loading data...',
    'max_size_100mb': 'Maximum size: 100 MB',
    'metric_attention': 'Attention',
    'metric_calmness': 'Calmness',
    'metric_engagement': 'Engagement',
    'metric_excitement': 'Excitement',
    'metric_interest': 'Interest',
    'metric_relaxation': 'Relaxation',
    'metric_stress': 'Stress',
    'metrics_comparison': 'Metrics Comparison',
    'metrics_details': 'Metrics Details',
    'nameLabel': 'Name',
    'neural_analysis': 'Neural Analysis',
    'new_user': 'New User',
    'no_data_to_export': 'No data to export',
    'no_eeg_results_for_perfume': 'No EEG results for this perfume',
    'outer_values_mean_higher': 'Outer values indicate higher scores',
    'pdf_export_error': 'PDF export error',
    'perfume_singular': 'Perfume',
    'perfumes_distribution_by_store': 'Perfume Distribution by Store',
    'personalityAnalysis': 'Personality Analysis',
    'phoneLabel': 'Phone Number',
    'profile_complete': 'Complete',
    'profile_incomplete': 'Incomplete',
    'profile_status': 'Profile Status',
    'recommendations': 'Recommendations',
    'registrationDateLabel': 'Registration Date',
    'release_date': 'Release Date',
    'reports_and_analytics': 'Reports and Analytics',
    'results_summary': 'Results Summary',
    'search_name_phone': 'Search by name or phone...',
    'select_apk_file': 'Select APK file',
    'select_apk_file_first': 'Select APK file first',
    'sensoryPreferencesTitle': 'Sensory Preferences',
    'statsTitle': 'Statistics',
    'this_month': 'This Month',
    'this_week': 'This Week',
    'this_year': 'This Year',
    'to_date': 'To Date',
    'total_tests': 'Total Tests',
    'traitFreshness': 'Freshness',
    'traitIntensity': 'Intensity',
    'traitSweetness': 'Sweetness',
    'traitWarmth': 'Warmth',
    'unknownValue': 'Unknown',
    'unspecifiedValue': 'Unspecified',
    'upload_new_update': 'Upload New Update',
    'upload_update': 'Upload Update',
    'update_uploaded_successfully': 'Update uploaded successfully',
    'uploading_file': 'Uploading file...',
    'userDetailsFallbackTitle': 'User Details',
    'users_activity_by_hour': 'Users Activity by Hour',
    'users_distribution': 'Users Distribution',
    'version_code': 'Version Code',
    'version_code_must_be_number': 'Version code must be a number',
    'version_name': 'Version Name',
    'store_login_title': 'Store Control Panel',
    'store_login_subtitle': 'Enter your store credentials',
    'username': 'Username',
    'password': 'Password',
    'login': 'Login',
    'please_enter_username': 'Please enter username',
    'please_enter_password': 'Please enter password',
    'password_min_6': 'Password must be at least 6 characters',
    'store_dashboard': 'Dashboard',
    'store_singular': 'Store',
    'logout': 'Logout',
    'store_not_found': 'Store not found',
    'please_enter_prefix': 'Please enter',
    'perfume_name': 'Perfume Name',
    'confirm_delete_perfume_title': 'Delete Perfume',
    'confirm_delete_perfume_message': 'Do you want to delete',
    'upload_perfumes_batch': 'Upload Perfume Batch',
    'upload_perfumes_batch_hint':
        'Download the template first, then upload the Excel file to add perfumes automatically.',
    'download_template': 'Download Template',
    'upload_excel': 'Upload Excel',
    'template_downloaded_success':
        'Excel template has been downloaded/saved successfully.',
    'template_saved_at': 'Template saved at:',
    'template_download_error': 'Template download error',
    'cannot_read_file': 'Unable to read file, choose another one.',
    'no_valid_perfumes_in_file': 'No valid perfumes found in the file.',
    'confirm_addition': 'Confirm Addition',
    'found_valid_perfumes': 'Valid perfumes found:',
    'invalid_rows': 'Invalid rows:',
    'add_valid_perfumes_question': 'Do you want to add valid perfumes?',
    'excel_read_error': 'File read error',
    'added_count': 'Added',
    'failed_count': 'Failed',
    'store_login_invalid_username': 'Invalid username',
    'store_login_invalid_password': 'Invalid password',
    'store_login_failed': 'Login failed',
    'intensity_light': 'Light',
    'intensity_medium': 'Medium',
    'intensity_strong': 'Strong',
    'sweetness_not_sweet': 'Not Sweet',
    'sweetness_light_sweet': 'Light Sweet',
    'sweetness_sweet': 'Sweet',
    'sweetness_very_sweet': 'Very Sweet',
    'warmth_cool': 'Cool',
    'warmth_neutral': 'Neutral',
    'warmth_warm': 'Warm',
    'subfamily_floral_soft': 'Soft Floral',
    'subfamily_floral_oriental': 'Floral Oriental',
    'subfamily_oriental_soft': 'Soft Oriental',
    'subfamily_oriental_woody': 'Oriental Woody',
    'subfamily_woods': 'Woods',
    'subfamily_mossy_woody': 'Mossy Woody',
    'subfamily_dry_woody': 'Dry Woody',
    'subfamily_citrus': 'Citrus',
    'subfamily_fruity': 'Fruity',
    'subfamily_green': 'Green',
    'subfamily_aquatic': 'Aquatic',
    'subfamily_fern': 'Fern',
  };
}
